# Generated by Django 4.0.6 on 2022-07-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_alter_client_mobile_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'potential'), (2, 'existent with at least one upcoming event.'), (3, 'existent with at least one past event.')], default=1),
        ),
    ]
