# Generated by Django 4.0.6 on 2022-07-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_client_client_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(default='old contract', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(default='old event', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(help_text='tick if the contract is signed'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.BooleanField(blank=True, default=False, help_text='green if the event already took place'),
        ),
    ]
